#ifndef _MEMORY_TEST_
#define _MEMORY_TEST_
void memory_test(void*);
x_thread alloc_thread;
x_thread calloc_thread;
x_thread realloc_thread;
x_thread tag_thread;
void alloc_prog(void*);
void calloc_prog(void*);
void realloc_prog(void*);
void tag_prog(void*);
#endif //_MEMORY_TEST_
