#!/bin/bash

#set -x
let n=0
PLOT="plot"
TEMP=""
while [ $1 ] ; do 
  let n=n+1
  grep "MEMORY STATUS" $1 | cut -d : -f2 | cut -d " " -f2 > $(dirname $1)/__$(basename $1)
  if [ $n -gt 1 ]; then
    PLOT=${PLOT}","
  fi
  PLOT=${PLOT}" \"$(dirname $1)/__$(basename $1)\" with lines"
  TEMP=${TEMP}" $(dirname $1)/__$(basename $1)" 
  shift
done

if [ $n -gt 0 ]; then
  {
  echo "set terminal png small color"                                         
  echo $PLOT 
  } | gnuplot > mauveplot.png
  echo "output written to file mauveplot.png"
  /bin/rm $TEMP
else
  echo "This script takes one or more mauve result files as input;"
  echo "from each input file it extracts the memory usage figures"
  echo "on the lines containing the message string 'MEMORY STATUS';"
  echo "it then plots the memory usage graph for each input file"
  echo "in a single png image which is written to file mauveplot.png"
  echo
  echo "usage $0 {<mauve results file> [...]}"

fi
