#!/bin/bash

###########################################################################
# Copyright (c) 2001 by Punch Telematix. All rights reserved.             #
#                                                                         #
# Redistribution and use in source and binary forms, with or without      #
# modification, are permitted provided that the following conditions      #
# are met:                                                                #
# 1. Redistributions of source code must retain the above copyright       #
#    notice, this list of conditions and the following disclaimer.        #
# 2. Redistributions in binary form must reproduce the above copyright    #
#    notice, this list of conditions and the following disclaimer in the  #
#    documentation and/or other materials provided with the distribution. #
# 3. Neither the name of Punch Telematix nor the names of other           #
#    contributors may be used to endorse or promote products derived      #
#    from this software without specific prior written permission.        #
#                                                                         #
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED          #
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF    #
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.    #
# IN NO EVENT SHALL PUNCH TELEMATIX OR OTHER CONTRIBUTORS BE LIABLE       #
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR            #
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF    #
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR         #
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,   #
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE    #
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN  #
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                           #
###########################################################################

# -----------------------------------------------------------------------------
if [ $# -eq 0 ] ; then
  echo ""
  echo "copies files or directory trees to server 'librarian' for backup"
  echo ""
  echo "usage1 : $0 {<sourcefile pathname> } [ <target dir> | <target file> ]"
  echo "usage2 : $0 {<sourcedir  pathname> } [ <target dir>]"
  echo "   default target dir is:"
  echo "   librarian.leuven.intern.acunia.com:/home/fs/OTF-read/intranet/"
  echo "        /OTF-teams/VMS/open-wonka-release/"
  echo "   if the source is one or more files, and the target is specified"
  echo "   but does not exist as a directory, it will be considered as a "
  echo "   new file name for the target."
  echo "   if the source is a directory and the target dir is specified"
  echo "   but does not exist, it will be considered as the new name for "
  echo "   copied directory tree."
  echo "   if a target dir is specified as a path, all but the lowest level"
  echo "   must specify an existing path in the default target dir."
  echo ""
  echo "examples :"
  echo "   cplib ./report/QAreport 0-8-1/report  # copies one file"
  echo "   cplib 0-8-1                           # copies directory tree "
else

  rcp -rp $1 vandeneede@librarian.leuven.intern.acunia.com:/home/fs/OTF-read/intranet/OTF-teams/VMS/open-wonka-release/$2
fi
