#!/bin/sh

###########################################################################
# Copyright (c) 2001 by Punch Telematix. All rights reserved.             #
#                                                                         #
# Redistribution and use in source and binary forms, with or without      #
# modification, are permitted provided that the following conditions      #
# are met:                                                                #
# 1. Redistributions of source code must retain the above copyright       #
#    notice, this list of conditions and the following disclaimer.        #
# 2. Redistributions in binary form must reproduce the above copyright    #
#    notice, this list of conditions and the following disclaimer in the  #
#    documentation and/or other materials provided with the distribution. #
# 3. Neither the name of Punch Telematix nor the names of other           #
#    contributors may be used to endorse or promote products derived      #
#    from this software without specific prior written permission.        #
#                                                                         #
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED          #
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF    #
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.    #
# IN NO EVENT SHALL PUNCH TELEMATIX OR OTHER CONTRIBUTORS BE LIABLE       #
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR            #
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF    #
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR         #
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,   #
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE    #
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN  #
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                           #
###########################################################################

if [ $# != '3' ]; then
  echo "Usage: $0 <linenumber of reportMemStat> <number of items> <color|monochrome|gray>"
  exit 1
fi

cat memstat | grep "reportMemStat:$1" | head -n $[$(cat memstat | grep -n Total | sed -e 's/\:.*//' | head -n 1) - 5] | sed -e 's/.*\ \:\ |//' | sed -e 's/|.*//' > fields

{ 
  export IFS='
'

  # echo set terminal png small color
  echo set terminal png small $3
  echo set format \"%.10g\"
  echo set size 1.25,1.25

  echo -n "plot [0:*] [0:*] "

  PLOT=$({
    for x in $(cat fields | head -n $2); do 
      y=$(echo $x | sed -e 's/ //g')
      grep "$x" memstat | awk '{print($10)}' > "_$y "
      echo -n "'_$y ' with lines, "
    done
  })

  CHARS=$(echo $PLOT | wc -c)
  PLOT=$(echo $PLOT | colrm $[$CHARS - 2])
  echo $PLOT
} | gnuplot > result.png

rm -rf _*
# rm -rf fields

eog result.png

