#!/bin/sh

if [ $# != '3' ]; then
  echo "Usage: $0 <linenumber of reportMemStat> <number of items> <color|monochrome|gray>"
  exit 1
fi

cat memstat | grep "reportMemStat:$1" | head -n $[$(cat memstat | grep -n Total | sed -e 's/\:.*//' | head -n 1) - 5] | sed -e 's/.*\ \:\ |//' | sed -e 's/|.*//' > fields

{ 
  export IFS='
'

  # echo set terminal png small color
  echo set terminal png small $3
  echo set format \"%.10g\"
  echo set size 1.25,1.25

  echo -n "plot [0:*] [0:*] "

  PLOT=$({
    for x in $(cat fields | head -n $2); do 
      y=$(echo $x | sed -e 's/ //g')
      grep "$x" memstat | awk '{print($10)}' > "_$y "
      echo -n "'_$y ' with lines, "
    done
  })

  CHARS=$(echo $PLOT | wc -c)
  PLOT=$(echo $PLOT | colrm $[$CHARS - 2])
  echo $PLOT
} | gnuplot > result.png

rm -rf _*
# rm -rf fields

eog result.png

