#!/bin/bash

# -------------------------------------------------------------------
# to be executed from within a build directory
if [ -f wonka ]; then
  if [ $2 ]; then
    ./wonka $1 com.acunia.wonka.test.awt.VisualTestEngine com.acunia.wonka.test.awt.$2
  else
  if [ $1 ]; then
    ./wonka  com.acunia.wonka.test.awt.VisualTestEngine  com.acunia.wonka.test.awt.$1
  else
    ./wonka  com.acunia.wonka.test.awt.VisualTestEngine
  fi
  fi
else
  echo "wonka executable not found."
  echo "this script is to be executed from within a build directory."
fi