/**************************************************************************
* Copyright (c) 2007 by Chris Gray, /k/ Embedded Java Solutions.          *
* All rights reserved.                                                    *
**************************************************************************/

package java.lang;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.IOException;
import java.util.Enumeration;
import java.util.Vector;
import java.util.Properties;

/*
** Package-protected class used to implement the built-in system properties.
** In practice this is a singleton, but we don't enforce this; the single
** instance is generated by the static initialiser of java.lang.System and
** used to create the system properties.
**
** The 1.4.2 API states that the following should always be defined:
** java.version
** java.vendor
** java.vendor.url
** java.home
** java.vm.specification.version
** java.vm.specification.vendor
** java.vm.specification.name
** java.vm.version
** java.vm.vendor
** java.vm.name
** java.specification.version
** java.specification.vendor
** java.specification.name
** java.class.version
** java.class.path
** java.library.path +
** java.io.tmpdir +
** java.compiler +
** java.ext.dirs
** os.name
** os.arch
** os.version
** file.separator
** path.separator
** line.separator
** user.name
** user.home
** user.dir
** + = new in 1.4
**
** We support all of these as best we can, except java.vm.specification.*
** and java.specification.* (for legal reasons).
**
** Sun JDK 1.4.2 seems also to define the following properties:
** java.runtime.name
** java.vm.name
**
** N.B. file.encoding should be one of the six mandatory encodings,
** in canonical form.
*/
class DefaultProperties extends Properties {

  DefaultProperties() {
    super(new NativeProperties());
    try {
      super.load(new ByteArrayInputStream("java.vm.name=Mika\njava.vm.version=1.4.2\njava.vendor=/k/ Embedded Java Solutions\njava.vendor.url=http://www.k-embedded-java.com\njava.vm.vendor=/k/ Embedded Java Solutions\njava.vm.name=Mika\njava.class.version=48.0\njava.class.path=this will be set later\nfile.separator=/\nfile.encoding=8859_1\npath.separator=:\nline.separator=\\n\n".getBytes("ISO-8859-1")));
    }
    catch (Throwable t) {
      t.printStackTrace();
    }
    if (get("user.language") == null) {
      put("user.language","en");
    }
  }

  public Object setProperty(String key, String value){
    throw new UnknownError("Someone trying to change a default property?");
  }

  public void load(InputStream in) throws IOException {
    throw new UnknownError("Someone trying to load the native properties?");
  }

  public Enumeration propertyNames() {
    Vector v = new Vector();
    Enumeration en = defaults.keys();
    while (en.hasMoreElements()) {
      v.add(en.nextElement());
    }
    en = keys();
    while (en.hasMoreElements()) {
      v.add(en.nextElement());
    }
    return v.elements();
  }

}

