#!/bin/bash

# -----------------------------------------------------------------------------
if [ $# -eq 0 ] ; then
  echo ""
  echo "copies files or directory trees to server 'librarian' for backup"
  echo ""
  echo "usage1 : $0 {<sourcefile pathname> } [ <target dir> | <target file> ]"
  echo "usage2 : $0 {<sourcedir  pathname> } [ <target dir>]"
  echo "   default target dir is:"
  echo "   librarian.leuven.intern.acunia.com:/home/fs/OTF-read/intranet/"
  echo "        /OTF-teams/VMS/open-wonka-release/"
  echo "   if the source is one or more files, and the target is specified"
  echo "   but does not exist as a directory, it will be considered as a "
  echo "   new file name for the target."
  echo "   if the source is a directory and the target dir is specified"
  echo "   but does not exist, it will be considered as the new name for "
  echo "   copied directory tree."
  echo "   if a target dir is specified as a path, all but the lowest level"
  echo "   must specify an existing path in the default target dir."
  echo ""
  echo "examples :"
  echo "   cplib ./report/QAreport 0-8-1/report  # copies one file"
  echo "   cplib 0-8-1                           # copies directory tree "
else

  rcp -rp $1 vandeneede@librarian.leuven.intern.acunia.com:/home/fs/OTF-read/intranet/OTF-teams/VMS/open-wonka-release/$2
fi