#!/bin/bash

# -------------------------------------------------------------------
     oldwonkas=$(pidof ./wonka)
    ./wonka gnu.testlet.TestRunner  &> /dev/null   &
    sleep 5
    allwonkas=$(pidof ./wonka)
    newwonkas=allwonkas

    if [ "$oldwonkas" = "$newwonkas" ]; then
      echo "MAUVE TESTS FAILED"
      echo "  can't execute 'wonka gnu.testlet.TestRunner'"
      echo "MAUVE TESTS FAILED  $(date +%Y/%m/%d%t%H:%M:%S)" >> $LOGFILE
      echo ""
      echo "  can't execute 'wonka gnu.testlet.TestRunner'"
    else


    for w in $oldwonkas; do
      newwonkas=$(echo $newwonkas | sed 's/'$w' //')
    done


      running=$(ps h --format time -p ${mauvepid} | cut -c1,2,4,5,7,8)
      let s=0
      while [ $running ] && [ $s -lt $maxtime ] ; do
        sleep $sleeptime
        let s=$s+$sleeptime
        running=$(ps h --format time -p ${mauvepid} | cut -c1,2,4,5,7,8)
      done

      if [ $s -gt $maxtime ]; then
        echo "MAUVE TESTS BUILD$b elapsed run time exceeds ${maxtime}s: aborted"
        echo "MAUVE TESTS BUILD$b elapsed run time exceeds ${maxtime}s: aborted $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
        kill -9 $mauvepid
      else

        if [ ! -s $RESULTS ]; then
          echo "MAUVE TESTS BUILD$b no results found : $BUILDDIR/$RESULTS"
          echo "MAUVE TESTS BUILD$b no results found : $BUILDDIR/$RESULTS  $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
        else
          alias grep=grep
          grep -a -e 'FAIL' $RESULTS  > mauve.fail
          diff mauve.fail ../refmauve.fail > mauve.diff
          if [ -s mauve.diff ]; then
            echo MAUVE TESTS BUILD$b FAILED
            echo "MAUVE TESTS BUILD$b FAILED  $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
            echo "-- expected fails -- " >> $LOGFILE
            cat ../refmauve.fail >> $LOGFILE
            echo "-- actual fails -- " >> $LOGFILE
            cat mauve.fail >> $LOGFILE
          else
            echo MAUVE TESTS BUILD$b PASSED
            echo "MAUVE TESTS BUILD$b PASSED  $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
          fi
          rm mauve.fail
          rm mauve.diff
        fi

      fi

    fi
