#!/bin/bash

###########################################################################
# Copyright (c) 2001 by Punch Telematix. All rights reserved.             #
#                                                                         #
# Redistribution and use in source and binary forms, with or without      #
# modification, are permitted provided that the following conditions      #
# are met:                                                                #
# 1. Redistributions of source code must retain the above copyright       #
#    notice, this list of conditions and the following disclaimer.        #
# 2. Redistributions in binary form must reproduce the above copyright    #
#    notice, this list of conditions and the following disclaimer in the  #
#    documentation and/or other materials provided with the distribution. #
# 3. Neither the name of Punch Telematix nor the names of other           #
#    contributors may be used to endorse or promote products derived      #
#    from this software without specific prior written permission.        #
#                                                                         #
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED          #
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF    #
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.    #
# IN NO EVENT SHALL PUNCH TELEMATIX OR OTHER CONTRIBUTORS BE LIABLE       #
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR            #
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF    #
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR         #
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,   #
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE    #
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN  #
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                           #
###########################################################################

#set -x
let n=0
PLOT="plot"
TEMP=""
while [ $1 ] ; do 
  let n=n+1
  grep "MEMORY STATUS" $1 | cut -d : -f2 | cut -d " " -f2 > $(dirname $1)/__$(basename $1)
  if [ $n -gt 1 ]; then
    PLOT=${PLOT}","
  fi
  PLOT=${PLOT}" \"$(dirname $1)/__$(basename $1)\" with lines"
  TEMP=${TEMP}" $(dirname $1)/__$(basename $1)" 
  shift
done

if [ $n -gt 0 ]; then
  {
  echo "set terminal png small color"                                         
  echo $PLOT 
  } | gnuplot > mauveplot.png
  echo "output written to file mauveplot.png"
  /bin/rm $TEMP
else
  echo "This script takes one or more mauve result files as input;"
  echo "from each input file it extracts the memory usage figures"
  echo "on the lines containing the message string 'MEMORY STATUS';"
  echo "it then plots the memory usage graph for each input file"
  echo "in a single png image which is written to file mauveplot.png"
  echo
  echo "usage $0 {<mauve results file> [...]}"

fi
