#!/bin/bash

###########################################################################
# Copyright (c) 2001 by Punch Telematix. All rights reserved.             #
#                                                                         #
# Redistribution and use in source and binary forms, with or without      #
# modification, are permitted provided that the following conditions      #
# are met:                                                                #
# 1. Redistributions of source code must retain the above copyright       #
#    notice, this list of conditions and the following disclaimer.        #
# 2. Redistributions in binary form must reproduce the above copyright    #
#    notice, this list of conditions and the following disclaimer in the  #
#    documentation and/or other materials provided with the distribution. #
# 3. Neither the name of Punch Telematix nor the names of other           #
#    contributors may be used to endorse or promote products derived      #
#    from this software without specific prior written permission.        #
#                                                                         #
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED          #
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF    #
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.    #
# IN NO EVENT SHALL PUNCH TELEMATIX OR OTHER CONTRIBUTORS BE LIABLE       #
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR            #
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF    #
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR         #
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,   #
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE    #
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN  #
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                           #
###########################################################################

# -------------------------------------------------------------------
     oldwonkas=$(pidof ./wonka)
    ./wonka gnu.testlet.TestRunner  &> /dev/null   &
    sleep 5
    allwonkas=$(pidof ./wonka)
    newwonkas=allwonkas

    if [ "$oldwonkas" = "$newwonkas" ]; then
      echo "MAUVE TESTS FAILED"
      echo "  can't execute 'wonka gnu.testlet.TestRunner'"
      echo "MAUVE TESTS FAILED  $(date +%Y/%m/%d%t%H:%M:%S)" >> $LOGFILE
      echo ""
      echo "  can't execute 'wonka gnu.testlet.TestRunner'"
    else


    for w in $oldwonkas; do
      newwonkas=$(echo $newwonkas | sed 's/'$w' //')
    done


      running=$(ps h --format time -p ${mauvepid} | cut -c1,2,4,5,7,8)
      let s=0
      while [ $running ] && [ $s -lt $maxtime ] ; do
        sleep $sleeptime
        let s=$s+$sleeptime
        running=$(ps h --format time -p ${mauvepid} | cut -c1,2,4,5,7,8)
      done

      if [ $s -gt $maxtime ]; then
        echo "MAUVE TESTS BUILD$b elapsed run time exceeds ${maxtime}s: aborted"
        echo "MAUVE TESTS BUILD$b elapsed run time exceeds ${maxtime}s: aborted $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
        kill -9 $mauvepid
      else

        if [ ! -s $RESULTS ]; then
          echo "MAUVE TESTS BUILD$b no results found : $BUILDDIR/$RESULTS"
          echo "MAUVE TESTS BUILD$b no results found : $BUILDDIR/$RESULTS  $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
        else
          alias grep=grep
          grep -a -e 'FAIL' $RESULTS  > mauve.fail
          diff mauve.fail ../refmauve.fail > mauve.diff
          if [ -s mauve.diff ]; then
            echo MAUVE TESTS BUILD$b FAILED
            echo "MAUVE TESTS BUILD$b FAILED  $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
            echo "-- expected fails -- " >> $LOGFILE
            cat ../refmauve.fail >> $LOGFILE
            echo "-- actual fails -- " >> $LOGFILE
            cat mauve.fail >> $LOGFILE
          else
            echo MAUVE TESTS BUILD$b PASSED
            echo "MAUVE TESTS BUILD$b PASSED  $(date +%Y/%m/%d%t%H:%M:%S)" > $LOGFILE
          fi
          rm mauve.fail
          rm mauve.diff
        fi

      fi

    fi
