#!/bin/sh

{ 

echo set terminal png small color
echo set format \"%.10g\"

echo -n "plot [0:*] [0:*] "

grep "$1" memstat | awk '{print($10)}' > "_$1"

echo -n "\"_$1\" with lines"

} | gnuplot > result2.png

rm -rf _*

eog result2.png

