#!/bin/bash

# -------------------------------------------------------------------
if [ $1 ] && [ $1 = -x ]; then
  set -x
  shift
fi
if [ $1 ] && [ $1 = -u ]; then
  update=true
  shift
fi
if [ $# -lt 2 ]; then
  echo "usage: $0 [-x] [-u] <tag> <file|directory ...> "
  echo "  updates 'file(s)' (if -u specified) from cvs repository in "
  echo "  the local directory; moves the specified tag in cvs "
  echo "  repository for these files; runs in verbose mode if -x specified"
  exit 1
fi
tag=$1
shift
if [ $update ]; then
  for f in $@; do
    cvs update -A $f
  done
fi
cvs tag -F $tag $@
set -