###########################################################################
# Copyright (C) 2009 by /k/ Embedded Java Solutions. All rights reserved. #
#                                                                         #
# Redistribution and use in source and binary forms, with or without      #
# modification, are permitted provided that the following conditions      #
# are met:                                                                #
# 1. Redistributions of source code must retain the above copyright       #
#    notice, this list of conditions and the following disclaimer.        #
# 2. Redistributions in binary form must reproduce the above copyright    #
#    notice, this list of conditions and the following disclaimer in the  #
#    documentation and/or other materials provided with the distribution. #
# 3. Neither the name of Punch Telematix or of /k/ Embedded Java Solutions#
#    nor the names of other contributors may be used to endorse or promote#
#    products derived from this software without specific prior written   #
#    permission.                                                          #
#                                                                         #
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED          #
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF    #
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.    #
# IN NO EVENT SHALL PUNCH TELEMATIX, /K/ EMBEDDED JAVA SOLUTIONS OR OTHER #
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,   #
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,     #
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR      #
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  #
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    #
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS      #
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.            #
###########################################################################

#  First output banner, #incudes, and a couple of utility functions

BEGIN {
  print " "
  print "/*"
  print "** This file is generated automatically from math-classes.in"
  print "** Do NOT edit this file."
  print "*/"
  print " "
  print "#include \"wstrings.h\""
  print "#include \"core-classes.h\""
  print "#include \"clazz.h\""
  print "#include \"fields.h\""
  print "#include \"hashtable.h\""
  print "#include \"jni.h\""
  print "#include \"locks.h\""
  print "#include \"methods.h\""
  print "#include \"ts-mem.h\""
  print "#include \"threads.h\""
  print "#include \"loading.h\""
  print "#include \"math-classes.h\""
  print " "

  module = "math"
  Module = "Math"
}

