#!/bin/bash

# -------------------------------------------------------------------
# to be executed from within a build directory
if [ -e fsroot ]; then
  if [ $1 ]; then
    java -cp fsroot/test/vte.jar com.acunia.wonka.test.awt.VisualTestEngine com.acunia.wonka.test.awt.$*
  else
    java -cp fsroot/system:fsroot/test/vte.jar com.acunia.wonka.test.awt.VisualTestEngine
  fi
else
  echo "classpath 'fsroot/test/vte.jar' not found."
  echo "this script is to be executed from within a build directory."
fi