#!/bin/bash

# -------------------------------------------------------------------
function checkTools() {
  if [ -z $RTTOOL ] ; then
    echo "Environment variable RTTOOL not defined. Cannot proceed."
    exit 1
  else
    source $RTTOOL/j_include
    if [ $? -ne 0 ]; then
      echo "Aborting ..."
      exit 1
    fi
  fi
}

# -------------------------------------------------------------------
function showHelp() {
  echo " This script creates main directory and neccessary sub-directories"
  echo " for unit testing a new open-wonka release."
  echo " usage: $0 {<open-wonka-release dir>}"
  echo "  e.g.: $0 0-8-2"
}

# -------------------------------------------------------------------

function getArgs () {

  if [ $1 ] && [ $1 = -x ]; then
    shift
    set -x
  fi

  if [ $# -ne 1 ]; then
    showHelp
    exit 1
  else
    if [ $1 = "--help" ] || [ $1 = "-h" ]; then
      showHelp
      exit 0
    else
      newdir=$1
    fi
  fi
}

# MAIN -------------------------------------------------------------------------

checkTools

newdir=
getArgs $@

mkdir $newdir
j_abort $?

mkdir $newdir/product
mkdir $newdir/report
mkdir $newdir/javadoc
mkdir $newdir/test-log
j_abort $?
mkdir $newdir/test-log/arm-anakin-linux
mkdir $newdir/test-log/arm-familiar-4.0
mkdir $newdir/test-log/x86-debian-potato
mkdir $newdir/test-log/x86-redhat-6.2
mkdir $newdir/test-log/x86-redhat-7.1
mkdir $newdir/test-log/x86-suse-7.2
#cp $RTTOOL/mkbuild $newdir
cp $RTTOOL/refmauve.fail $newdir

