#!/bin/bash

# -------------------------------------------------------------------
#set -x
if [ -d build1 ] || [ -d build2 ] || [ -d build3 ] || [ -d build4 ] || [ -d build5 ] ||
   [ -d build6 ] || [ -d build7 ] || [ -d build8 ] || [ -d build9 ] || [ -d build10 ] ||
   [ -d open-wonka ] || [ -d test-log ]; then
   echo "nothing copied, clean up first"
   exit
fi

if [ ! -f report/QAreport ] ; then
  echo "./report/QAreport not found. Nothing copied"
else
if [ ! -f javadoc.tar.gz ] ; then
  echo "./javadoc.tar.gz not found. Nothing copied"
else
if [ ! -f refmauve.fail ] ; then
  echo "./refmauve.fail not found. Nothing copied"
else
  LIBRARIAN=librarian.leuven.intern.acunia.com
  RELEASEDIR=/home/fs/OTF-read/intranet/OTF-teams/VMS/open-wonka-release/
  RELEASE=$(basename $PWD)
  RELEASENAME=$(echo $RELEASE | sed s/-/./g)
if [ ! -f product/wonka-bin-arm-linux-$RELEASENAME-release.tar.gz ] ; then
  echo "./product/wonka-bin-arm-linux-$RELEASENAME-release.tar.gz not found. Nothing copied"
else
if [ ! -f ./product/wonka-bin-x86-linux-$RELEASENAME-release.tar.gz ] ; then
  echo "product/wonka-bin-x86-linux-$RELEASENAME-release.tar.gz not found. Nothing copied"
else
if [ ! -f product/wonka-src-$RELEASENAME-release.tar.gz ] ; then
  echo "./product/wonka-src-$RELEASENAME-release.tar.gz not found. Nothing copied"
else
if [ ! -f product/open-wonka-$RELEASENAME-1.i386.rpm ] ; then
  echo "./product/open-wonka-$RELEASENAME-1.i386.rpm not found. Nothing copied"
else
if [ ! -f test-log.tar.gz ] ; then
  echo "./test-log.tar.gz not found. Nothing copied"



  echo "copying release WONKA-${RELEASE}-RELEASE ..."

  # core of the backup:
  # copy this directory, recursively with preservation of file attributes


  rcp -rp $PWD $(whoami)@LIBRARIAN:${RELEASEDIR}

fi
fi
fi
fi
fi
fi
fi
fi
